### ISSUE TITLE
Add loading indicator when press login

### ISSUE THREAD

**Issue by vanessaforney** [vanessaforney/woods-humane-society#14]
Sometimes connection is slow at the shelter and people were confused and tapping the screen

**Comment by ccarroll511** [comment]
Added the activity indicator when logging in.

**Comment by vanessaforney** [comment]
Thanks!

A few issues:
1. if you click login with no fields the indicator doesn't stop
2. Indicator should be slightly larger, centered in between the two text fields, and Util.blueColor()
3. If you click create account with invalid fields indicator doesn't stop.

**Comment by ccarroll511** [comment]
Fixed activity indicator when it appears and disappears.
