### ISSUE TITLE
Approve users on the app

### ISSUE THREAD

**Issue by vanessaforney** [vanessaforney/woods-humane-society#27]
should have a triple bar on top left that pulls out options to log out or approve users

**Comment by vanessaforney** [comment]
I made it so staff can click on Wood's and it takes you to a list of unverified users. When you click on the user, you are prompted with an alert to verify them or not.

Here's what we want it to be:
**Hamburger side menu**: instead of the log out button, should have the hamburger menu button.

![highlights](https://cloud.githubusercontent.com/assets/92667/13618289/2bdc9f62-e538-11e5-9344-d71c98916f3e.png)
![non-highlighted](https://cloud.githubusercontent.com/assets/92667/13618291/2ef338c8-e538-11e5-94df-f276231488ef.png)

**Comment by ccarroll511** [comment]
Done
