### ISSUE TITLE
Fix ManageUsers

### ISSUE THREAD

**Issue by vanessaforney** [vanessaforney/woods-humane-society#35]
Segmented control at the top:
Requests | Volunteers | Staff

**Requests** (non-verified users) ->
1. swipe to delete. click on delete: “Delete Request” “Are you sure you wish to delete this user?” Delete red.
2.  tap to make a volunteer or staff. (3 options: Make Volunteer, Make Staff, Cancel).

  **Volunteers** (verified users that are NOT staff) ->
1. swipe to delete: click on delete. “Delete User” “Are you sure you wish to delete this user?” Delete red. 
2. tap to make a staff member (2 options: Make Staff, Cancel)  

**Staff** (verified users that are staff) ->
1. swipe to delete: click on delete: “Delete User” “Are you sure you wish to delete this user?”  Delete red 
2. tap to make volunteer (2 options: Make Volunteer, Cancel)

--> Delete request: delete the **verified field** and the **staff field** from the user. keep their other info in case they make a mistake, we can fix manually on firebase
--> Make volunteer: set the **verified field** to true and **remove value of staff**
--> Make staff: set the **staff field** and **volunteer field** to true

**Comment by ccarroll511** [comment]
Everything is done but testing of deleting users needs to be done still.  This can be tested once the new side menu is put into the app

**Comment by vanessaforney** [comment]
Things to consider:
- What happens if you delete yourself as a staff while viewing?
- How does the alert work for logging out?

**Comment by vanessaforney** [comment]
Alert pops up while menu is open.
Delete yourself and you are logged out.
